In [ ]:
import pandas as pd
rateinfo = pd.read_csv('dataset/AmazonBook/Books_rating.csv')

In [5]:
rateinfo.shape

(3000000, 10)

In [3]:
### Filter for positive reviews(Changing the logic for filtering the reviews)
sep = 4
rateinfo_filtered = rateinfo.dropna(subset=['User_id'])
filtered_reviews = rateinfo_filtered[rateinfo_filtered['review/score'] >= sep]

In [6]:
filtered_reviews.shape

(1954505, 10)

In [7]:
filtered_reviews.head()

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...

In [12]:
columns = ['User_id', 'Id', 'review/text', 'review/summary']
filtered_reviews_save = filtered_reviews[columns]
filtered_reviews_save = pd.DataFrame(filtered_reviews_save, columns=columns)
filtered_reviews_save.to_csv(f'./dataset/AmazonBook/data_all.csv', index=False)
filtered_reviews_save.head()

,User_id,Id,review/text,review/summary
0,AVCGYZL8FQQTD,1882931173,This is only for Julie Strain fans. It's a col...,Nice collection of Julie Strain images
1,A30TK6U7DNS82R,0826414346,I don't care much for Dr. Seuss but after read...,Really Enjoyed It
2,A3UH4UZ4RSVO82,0826414346,"If people become the books they read and if ""t...",Essential for every personal and Public Library
3,A2MVUWT453QH61,0826414346,"Theodore Seuss Geisel (1904-1991), aka &quot;D...",Phlip Nel gives silly Seuss a serious treatment
4,A22X4XUPKF66MR,0826414346,Philip Nel - Dr. Seuss: American IconThis is b...,Good academic overview